spring:
  main:
    web-application-type: none
  application:
    name: toj_judge
  profiles:
    include: typemap, language-support

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: thinkpadx201

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 10
